### PR TITLE
[Retrofit Integration] - Integrates Retrofit and call JSONPlaceholder…

### PR DESCRIPTION
**Pull request by sgbcoder**
**Issue Link:** https://github.com/SuranjanDaw/Android-Java-Hacktoberfest-2019/issues/2

This PR integrates retrofit library into the app and in the Homepage screen calls the below url:
https://jsonplaceholder.typicode.com/users/1/posts
and populates the list of Posts for only user 1

**Note:** This PR will just populate the title and body of the first post.Further PR may be needed to add Recycler view functionality for displaying all the posts for a user.

### CODE REVIEW

**Comment by SuranjanDaw** [comment]
resolve the merge conflict

**Comment by sgbcoder** [comment]
PR #11 seems to have broken the build @SuranjanDaw, getting multiple build errors. Also local.properties seems to have been committed with the users sdk location.

**Comment by sgbcoder** [comment]
@SuranjanDaw have resolved the conflicts but the .gitignore didnt have anything in the previous commit due to which all the generated files keep showing up in the staged changes.
Would be willing to help out adding CI for the project.

**Comment by SuranjanDaw** [comment]
Great Work. Your rock @sgbcoder

**Pull request merged**
